apiVersion: v1
kind: ConfigMap
metadata:
  name: oauth-config
data:
  # Server HTTP settings
  APP_SERVER_HTTP_PORT: "8080"
  APP_SERVER_HTTP_HOST: ""
  APP_SERVER_HTTP_PRODUCTION: "true"
  APP_SERVER_HTTP_BASEPATH: "oauth2"

  # Server domain URL
  APP_SERVER_DOMAINURL: "https://app.gw.k8s.sh.aban.io"

  # Service Scheduler settings
  APP_SERVICE_SCHEDULER_ENABLED: "false"
  APP_SERVICE_SCHEDULER_INTERVAL: "3s"

  # OAuth settings
  APP_OAUTH_CLIENTID: "example-app"
  APP_OAUTH_CLIENTSECRET: "ZXhhbXBsZS1hcHAtc2VjcmV0"
  APP_OAUTH_PROVIDERURL: "https://app.gw.k8s.sh.aban.io/dex"

  # Security settings
  APP_SECURITY_SECRET: "W+c%1*~(E)^2^#sxx^^7%b34"

  # Observability Tracing settings
  APP_OBSERVABILITY_TRACING_ENABLED: "false"
  APP_OBSERVABILITY_TRACING_ZIPKIN_URL: "http://localhost:9411/api/v2/spans"
  APP_OBSERVABILITY_TRACING_ZIPKIN_SERVICENAME: "greeter"

  # Observability Metrics settings
  APP_OBSERVABILITY_METRICS_ENABLED: "false"
  APP_OBSERVABILITY_METRICS_PROMETHEUS_PORT: "9090"
  APP_OBSERVABILITY_METRICS_PROMETHEUS_HOST: "localhost"
  APP_OBSERVABILITY_METRICS_PROMETHEUS_PATH: "/metrics"

  # Observability Logging settings
  APP_OBSERVABILITY_LOGGING_LEVEL: "info"
  APP_OBSERVABILITY_LOGGING_LOGSTASH_ENABLED: "false"
  APP_OBSERVABILITY_LOGGING_LOGSTASH_ADDRESS: "127.0.0.1:9000"
