apiVersion: v1
kind: ConfigMap
metadata:
  name: rules
data:
  rules.yaml: >
    rules:
      - name: defualt
        path: /
        action: auth
      - name: swagger
        path: /api/v1/docs
        action: allow
      - name: api
        path: /api/
        action: deny