server:
  http:
    port: 8080
    host: ""
    production: true

service:
  auth:
    jwt:
      secret: "f59V5CxMRofgBXe9B63mC3dTy/vaORfe0pFHj7qBPPAt"
  scheduler:
    enabled: false
    interval: "3s"

datasource:
  postgres: 
    dsn: "host=localhost user=postgres password=postgres dbname=idp sslmode=disable TimeZone=UTC"
    connection_pool_enabled: true
    connection_pool_max_idle: 10
    connection_pool_max_open: 100
    connection_pool_max_lifetime: "1h"
    connection_pool_max_idle_time: "1h"
    connection_pool_health_check_period: "1m"
    connection_pool_health_check_timeout: "1s"
    enabled: true
  redis:
    Enabled: false
    Address: localhost:6379
    Password: ""
    DB: ""
observability:
  tracing:
    enabled: false
    zipkin:
      url: "http://localhost:9411/api/v2/spans"
      service_name: "greeter"
  metrics:
    enabled: false
    prometheus:
      port: 9090
      host: "localhost"
      path: "/metrics"
  logging:
    level: "debug"
    logstash:
      enabled: false
      address: "127.0.0.1:9000"
