version: '3.9'

services:

  postgres:
    image: postgres:12.20
    container_name: postgres
    restart: "no"
    network_mode: host
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: idp

