apiVersion: v1
kind: Service
metadata:
  name: farin-vehicle-record-svc
spec:
  type: ClusterIP
  selector:
    app: farin-vehicle-record
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    name: rest
